### ISSUE TITLE
CSS::Minifier::XS breaks hsl()

### ISSUE THREAD

**Issue by bleargh45** [bleargh45/CSS-Minifier-XS#3]
Migrated from [rt.cpan.org #90879](https://rt.cpan.org/Ticket/Display.html?id=90879) (status was 'open')

Requestors:
* soehnlein@nureg.de

Attachments:
* [zero-units-commafied.css](https://rt.cpan.org/Ticket/Attachment/1297985/687561/zero-units-commafied.css)
* [zero-units-commafied.min](https://rt.cpan.org/Ticket/Attachment/1297985/687562/zero-units-commafied.min)
* [zero-units-commafied.css](https://rt.cpan.org/Ticket/Attachment/1300684/689133/zero-units-commafied.css)
* [zero-units-commafied.min](https://rt.cpan.org/Ticket/Attachment/1300684/689134/zero-units-commafied.min)

From http://oid.philipp-soehnlein.de/ on 2013-11-28 15:55:06
:

The W3C specification of the CSS hsl()- and hsla()-color functions says:
'Saturation and lightness are represented as percentages.'
(see http://www.w3.org/TR/2003/CR-css3-color-20030514/#hsl-color).

CSS::Minifier::XS removes the percentage sign of the saturation value and therefore breaks the hsl()- and hsla()-color-functions. Here is an example:
.foo { background-color: hsl(0,50%,50%); }
becomes
.foo { background-color: hsl(0,50,50%); }
which is not valid CSS and browsers ignore the background-color property.

**Comment by bleargh45** [comment]
From gtermars@cpan.org on 2013-12-03 18:29:11
:

On Thu Nov 28 10:55:06 2013, http://oid.philipp-soehnlein.de/ wrote:
> CSS::Minifier::XS removes the percentage sign of the saturation value
> and therefore breaks the hsl()- and hsla()-color-functions. Here is an
> example:
> .foo { background-color: hsl(0,50%,50%); }
> becomes
> .foo { background-color: hsl(0,50,50%); }

Philipp, I'm trying to reproduce this with the CSS that you've provided, but am unable to do so w/v0.09.

Took your CSS, created a pair of new files in "t/css/", and then ran the "t/02-minify.t" test, and it came out as expected (with the percentage on both of the 50s).

I've attached the files I have to this ticket.  If you would be kind enough to download v0.09, and drop these files into the "t/css/" directory, run "perl Build.PL; ./Build; prove -bv t/02-minify.t", and attach the output back here, I'd appreciate it greatly.

**Comment by bleargh45** [comment]
From http://oid.philipp-soehnlein.de/ on 2013-12-11 12:38:47
:

You are right, my provided test case was wrong, because I thought it happens to the second value everytime. Actually the problem is, when the second (or the third) value is zero, the percent sign must still be there. I tested this behaviour in Firefox 26, Safari 5.1.10, Chrome 31 and Opera 18 and every one of these browsers drop the background-color declaration if the percent sign is missing for the second and third value, even if its zero. Browsers probably behave like that because the specification says "Saturation and lightness are represented as percentages."

Find attached some updated test files.

**Comment by PitWenkin** [comment]
Can confirm this on Chrome 88 & Safari 14

**Comment by PitWenkin** [comment]
Working CSS befoe minifying:
```
background: -webkit-gradient(linear,left top, left bottom, from(hsla(0,0%,100%,0)), to(white));
background: linear-gradient(to bottom, hsla(0,0%,100%,0), white));
```

Is minified to:

`background:-webkit-gradient(linear,left top,left bottom,from(hsla(0,0,100%,0)),to(white));background:linear-gradient(to bottom,hsla(0,0,100%,0),white);`

which does not work

**Comment by bleargh45** [comment]
@PitWenkin ... which version are you seeing that behaviour with?

Am running your CSS through the current v0.11 release, and am seeing that the percent signs are properly preserved in the resulting CSS.

Using your starting CSS of:
```
background: -webkit-gradient(linear,left top, left bottom, from(hsla(0,0%,100%,0)), to(white));
background: linear-gradient(to bottom, hsla(0,0%,100%,0), white));
```

I see that it gets minified to:
```
background:-webkit-gradient(linear,left top,left bottom,from(hsla(0,0%,100%,0)),to(white));background:linear-gradient(to bottom,hsla(0,0%,100%,0),white));
```

which includes the second `hsla(0,0%,100%,0)` that your example above shows as incorrect (with `0` instead of `0%`)

**Comment by PitWenkin** [comment]
I had the bug in version 0.10. (It was not possible to update to 0.11 two days ago?)
I was now able to update to 0.12 which fixes the bug.

**Comment by bleargh45** [comment]
Fabulous!  Glad to hear that this has addressed the issue for you.  Thank you for the quick response!
